// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV-AgjeQKeT1pAumB0k5tiHPPXVFyAJGs',
    appId: '1:943881354663:web:1bf53701f827971c5e8a82',
    messagingSenderId: '943881354663',
    projectId: 'shopify-ca467',
    authDomain: 'shopify-ca467.firebaseapp.com',
    storageBucket: 'shopify-ca467.firebasestorage.app',
    measurementId: 'G-65DRWW8914',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdroCb4ZeC-SzoxKPNGVLg92nU6W8nwxw',
    appId: '1:943881354663:android:87b7abdb1bb136ab5e8a82',
    messagingSenderId: '943881354663',
    projectId: 'shopify-ca467',
    storageBucket: 'shopify-ca467.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiQgb5uQmE0c5LepRVDzSeX2G7RNgCeC0',
    appId: '1:943881354663:ios:145550b6c000d9815e8a82',
    messagingSenderId: '943881354663',
    projectId: 'shopify-ca467',
    storageBucket: 'shopify-ca467.firebasestorage.app',
    iosClientId: '943881354663-50n4mccj82b0i6ds0bm29a62bm7c7ut4.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopify',
  );

}